# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Builder stage
FROM golang:1.23-alpine AS builder
RUN apk add --no-cache git ca-certificates
WORKDIR /app
# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download
# Copy source
COPY . .
# Build binary (smaller, static-ish)
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o bgg-mcp main.go

# Final stage
FROM alpine:3.19
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/bgg-mcp /usr/local/bin/bgg-mcp
RUN chmod +x /usr/local/bin/bgg-mcp

LABEL io.modelcontextprotocol.server.name="io.github.kkjdaniel/bgg-mcp"

EXPOSE 8080
ENV MCP_MODE=http
ENV MCP_PORT=8080

HEALTHCHECK --interval=30s --timeout=5s --retries=3 CMD wget -qO- http://localhost:8080/health || exit 1

ENTRYPOINT ["/usr/local/bin/bgg-mcp"]
CMD ["-mode","http","-port","8080"]
